apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
        label: label
    spec:
      containers:
      - name: calculator
        image: htetmyatisgod/calculator:2.0
        ports:
        - containerPort: 8080
# 👉 PUT env HERE (inside container)
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/calculator"
        - name: SPRINGDOC_API_DOCS_PATH
          value: "/calculator/v3/api-docs"
        - name: SPRINGDOC_SWAGGER_UI_PATH
