apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort                # exposes the app on a port on all nodes
  selector:
    app: calculator            # matches the Deployment pods
  ports:
    - protocol: TCP
      port: 8080              # port inside the cluster
      targetPort: 8080       # container port in pods
      nodePort: 30080          # external port on localhost