- name: Deploy to Kubernetes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Apply deployment
      shell: kubectl apply -f {{ playbook_dir }}/../deployment.yaml --validate=false

    - name: Apply service
      shell: kubectl apply -f {{ playbook_dir }}/../service.yaml --validate=false